### ISSUE TITLE
Unhandled Exception has occurred in your application.

### ISSUE THREAD

**Issue by leptoid** [LenAnderson/DumbContactSheetMaker#1]
So I get this when I have subfolders under a directory named 1 (my root folder), but no files in the root folder.  I want to create Contact SHeets for all the subfolders, so I said "hey, move them all to one folder..."  nope.  Crash!  If I put a JPG into folder "1", this crashing stops.  Essentially the folder demands a file be in the root folder.
![image](https://user-images.githubusercontent.com/18079714/36100819-2719010c-0fcd-11e8-85c8-ca7d92335c8a.png)

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentOutOfRangeException: Value of '1' is not valid for 'Value'. 'Value' should be between 'minimum' and 'maximum'.
Parameter name: Value
   at System.Windows.Forms.ProgressBar.set_Value(Int32 value)
   at DumbContactSheetMaker.MainForm.UpdateStatus(Int32 step, Int32 stepMax, String statusPrefix, String status)
   at DumbContactSheetMaker.MainForm.<>c__DisplayClass3_0.<UpdateStatus>b__0()


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2600.0 built by: NET471REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
DumbContactSheetMaker
    Assembly Version: 1.1.0.0
    Win32 Version: 1.1.0.0
    CodeBase: file:///D:/Pictures/DumbContactSheetMaker.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2600.0 built by: NET471REL1LAST
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Comment by leptoid** [comment]
Better explanation of folder structure:
Does not work or causes exception errors (OS = Win10x64)
```
Folder PATH listing for volume Data D
Volume serial number is 1234-1234
D:.
|   
\---1
    +---pic
    |       1491071775986.png
    |       a2378b04a11a28651e65db78436ce269.jpg
    |       buythings.jpg
    |       
    \---pics2
            eJwVyMsNwyAMANBdGABjML9sgwglSEkdgXuqunvb05PeW73mqTZ1iNxrA9jHqjx3vYRn6U135n62co-lK19QREo9rvaUBTb74FJKGDGQIWvpV8FRRh_8H5NjBKRsKEeHloh0Hw_1-QK_ySJz.Cq03D--wD4jQHmOvmTv9ok1n4JU.gif
            quote-it-s-just-that-it-s-mind-boggling-to-me-how-many-people-i-encounter-every-day-who-are-struggling-to-merlin-mann-249734.jpg
            Spot_the_cow.gif
            tumblr_o0nyloJ7y81v44yceo1_500.jpg
```
Does work. (OS = Win10x64)
```
Folder PATH listing for volume Data D
Volume serial number is 1234-1234
D:.
|   
\---1
    |   buythings.jpg
    |   
    +---pic
    |       1491071775986.png
    |       a2378b04a11a28651e65db78436ce269.jpg
    |       buythings.jpg
    |       
    \---pics2
            eJwVyMsNwyAMANBdGABjML9sgwglSEkdgXuqunvb05PeW73mqTZ1iNxrA9jHqjx3vYRn6U135n62co-lK19QREo9rvaUBTb74FJKGDGQIWvpV8FRRh_8H5NjBKRsKEeHloh0Hw_1-QK_ySJz.Cq03D--wD4jQHmOvmTv9ok1n4JU.gif
            quote-it-s-just-that-it-s-mind-boggling-to-me-how-many-people-i-encounter-every-day-who-are-struggling-to-merlin-mann-249734.jpg
            Spot_the_cow.gif
            tumblr_o0nyloJ7y81v44yceo1_500.jpg
```

**Comment by leptoid** [comment]
How long has it been since anyone has used the "tree" command?! haha

**Comment by LenAnderson** [comment]
Hmm. I can't seem to reproduce this exception. It only happens for me when one of the leaves (a folder without subfolders) is empty or the "Recursive" checkbox is not active. Which kinda makes sense because contact sheets are only created if a folder does not contain subfolders (when recursive).

Still something that needs to be fixed, but I don't get any errors when trying to create your scenario.
